---
abstract: 'very simple DBI wrapper/ORMapper'
author:
  - 'Atsushi Kobayashi  C<< <nekokak __at__ gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: '6.36'
  Test::Mock::Guard: '0'
  Test::More: '0.96'
  Test::Requires: '0'
  Test::SharedFork: '0.15'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Teng
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Teng:
    file: lib/Teng.pm
    version: '0.25'
  Teng::Iterator:
    file: lib/Teng/Iterator.pm
  Teng::Plugin::BulkInsert:
    file: lib/Teng/Plugin/BulkInsert.pm
  Teng::Plugin::Count:
    file: lib/Teng/Plugin/Count.pm
  Teng::Plugin::FindOrCreate:
    file: lib/Teng/Plugin/FindOrCreate.pm
  Teng::Plugin::Lookup:
    file: lib/Teng/Plugin/Lookup.pm
  Teng::Plugin::Pager:
    file: lib/Teng/Plugin/Pager.pm
  Teng::Plugin::Pager::MySQLFoundRows:
    file: lib/Teng/Plugin/Pager/MySQLFoundRows.pm
  Teng::Plugin::Replace:
    file: lib/Teng/Plugin/Replace.pm
  Teng::Plugin::SQLPager:
    file: lib/Teng/Plugin/SQLPager.pm
  Teng::Plugin::SingleBySQL:
    file: lib/Teng/Plugin/SingleBySQL.pm
  Teng::QueryBuilder:
    file: lib/Teng/QueryBuilder.pm
  Teng::Row:
    file: lib/Teng/Row.pm
  Teng::Schema:
    file: lib/Teng/Schema.pm
  Teng::Schema::Declare:
    file: lib/Teng/Schema/Declare.pm
  Teng::Schema::Dumper:
    file: lib/Teng/Schema/Dumper.pm
  Teng::Schema::Loader:
    file: lib/Teng/Schema/Loader.pm
  Teng::Schema::Table:
    file: lib/Teng/Schema/Table.pm
requires:
  Carp: '0'
  Class::Accessor::Lite: '0.05'
  Class::Load: '0.06'
  DBI: '1.33'
  DBIx::Inspector: '0.06'
  DBIx::TransactionManager: '1.06'
  Data::Page: '0'
  Data::Page::NoTotalEntries: '0.02'
  SQL::Maker: '0.14'
  parent: '0'
resources:
  bugtracker: https://github.com/nekokak/p5-Teng/issues
  homepage: https://github.com/nekokak/p5-Teng
  repository: git://github.com/nekokak/p5-Teng.git
version: '0.25'
x_authority: cpan:NEKOKAK
x_contributors:
  - 'Yuki Ibe <yibe@yibe.org>'
  - 'libkenta <libkenta@gmail.com>'
  - 'lestrrat <lestrrat+github@gmail.com>'
  - 'Masahiro Honma <hiratara@cpan.org>'
  - 'makamaka <makamaka.donzoko@gmail.com>'
  - 'Nishibayashi Takuji <takuji@senchan.jp>'
  - 'zentooo <ankerasoy@gmail.com>'
  - 'Atsushi Kobayashi <nekokak _at_ gmail dot com>'
  - 'Tomohiro Hosaka <bokutin@bokut.in>'
  - 'issm <issmxx@gmail.com>'
  - 'Atsushi Kato <ktat@cpan.org>'
  - 'ktat <ktat.is@gmail.com>'
  - 'Kazuhiro Osawa <yappo@shibuya.pl>'
  - 'Masahiro Chiba <chiba@everqueue.com>'
  - 'Atsushi Kobayashi <nekokak@gmail.com>'
  - 'Jun Kuriyama <kuriyama@s2factory.co.jp>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
  - 'k-sato <k-sato@mfac.jp>'
  - 'ITO Nobuaki <daydream.trippers@gmail.com>'
  - 'karupanerura <karupa@cpan.org>'
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
  - 'Geraud CONTINSOUZAS <geraud@hyaku.nijuu.nana>'
  - 'moznion <moznion@gmail.com>'
  - 'Songmu <y.songmu@gmail.com>'
  - 'nobuoka <nobuoka@vividcode.info>'
  - 'Kazuho Oku <kazuhooku@gmail.com>'
  - 'cho45 <cho45@lowreal.net>'
