---
abstract: 'very simple DBI wrapper/ORMapper'
author:
  - 'Atsushi Kobayashi  C<< <nekokak __at__ gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.96
  Test::SharedFork: 0.15
  Test::mysqld: 0
  Test::postgresql: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Teng
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Class::Accessor::Lite: 0.05
  Class::Load: 0.06
  DBI: 0
  DBIx::Inspector: 0.03
  DBIx::TransactionManager: 1.06
  Data::Page: 0
  Data::Page::NoTotalEntries: 0.02
  SQL::Maker: 0.08
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/nekokak/p5-Teng.git
version: 0.07
